name: Cats 😺

on:
  pull_request: {}

jobs:
  echoVars:
    name: echo vars
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event.event_type }}
          echo ${{ github.event_name }}
          echo ${{ github.event.name }}
  aCatForCreatingThePullRequest:
    if: github.event.event_type == 'opened'
    name: A cat for your effort!
    runs-on: ubuntu-latest
    steps:
      - name: Action Cats
        uses: ruairidhwm/action-cats@1.0.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
