name: PR 😎

on:
  pull_request: {}

jobs:
  build:
    name: "🛠 Build editor (${{ matrix.targetPlatform }})."
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          # This list of target platforms is based on Ubuntu as a base platform
          # Linux Build Support
          # - linux-mono # May not exist in newer versions / May be default for Ubuntu
          - linux-il2cpp # May not exist in older versions

          # Windows Build Support
          - windows-mono
          # - windows-il2cpp # May not exist for ubuntu

          # MacOS Build Support
          - mac-mono
          # - mac-il2cpp # May not exist for ubuntu

          # iOS Build Support
          - ios

          # Android Build Support
          - android

          # WebGL Build support
          - webgl

          # Non-priorities: (but able to support)
          #  - vuforia-ar # Vuforia Augmented Reality Support
          #  - appletv # tvOS Build Support
          #  - samsung # SamsungTV Build Support
          #  - tizen # Tizen Build Support
          #  - lumin # Lumin OS (Magic Leap) Build Support

          # Language packs:
          #  - language-ja
          #  - language-ko
          #  - language-zh-cn
          #  - language-zh-hant
          #  - language-zh-hans

          # Tools: (probably included in build support packs)
          # - android-sdk-ndk-tools # Android SDK & NDK Tools
          # - android-open-jdk # OpenJDK
          # - monodevelop # MonoDevelop / Unity Debugger

    steps:
      ###########################
      #          Setup          #
      ###########################
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.targetPlatform }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.targetPlatform }}
            ${{ runner.os }}-buildx-
      #      - name: Login to DockerHub
      #        uses: docker/login-action@v1
      #        with:
      #          username: ${{ secrets.DOCKERHUB_USERNAME }}
      #          password: ${{ secrets.DOCKERHUB_TOKEN }}

      ###########################
      #    Free disk space   #
      ###########################
      - name: Free disk space
        run: .github/workflows/scripts/free_disk_space.sh

      ###########################
      #        Base image       #
      ###########################
      - name: Build base image # and push
        uses: docker/build-push-action@v2
        id: build_base_image
        with:
          context: .
          file: ./base/Dockerfile
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: true
          tags: localhost:5000/unityci/base:latest
      - name: Inspect
        run: |
          docker buildx imagetools inspect localhost:5000/unityci/base:latest
      #      - name: Image digest
      #        run: echo ${{ steps.build_base_image.outputs.digest }}
      #      - name: Update DockerHub description
      #        uses: peter-evans/dockerhub-description@v2
      #        with:
      #          username: ${{ secrets.DOCKERHUB_USERNAME }}
      #          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      #          repository: peterevans/dockerhub-description
      #          short-description: $(cat ./base/100-characters-dockerhub-description.txt)
      #          readme-filepath: ./base/README.md

      ###########################
      #        Hub image        #
      ###########################
      - name: Build hub image # and push
        uses: docker/build-push-action@v2
        id: build_hub_image
        with:
          context: .
          file: ./hub/Dockerfile
          build-args: baseImage=localhost:5000/unityci/base:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: true
          tags: localhost:5000/unityci/hub:latest
      - name: Inspect
        run: |
          docker buildx imagetools inspect localhost:5000/unityci/hub:latest
      #      - name: Image digest
      #        run: echo ${{ steps.build_hub_image.outputs.digest }}
      #      - name: Update DockerHub description
      #        uses: peter-evans/dockerhub-description@v2
      #        with:
      #          username: ${{ secrets.DOCKERHUB_USERNAME }}
      #          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      #          repository: peterevans/dockerhub-description
      #          short-description: $(cat ./hub/100-characters-dockerhub-description.txt)
      #          readme-filepath: ./hub/README.md

      ###########################
      #       Editor image      #
      ###########################
      - name: Build editor image # and push
        uses: docker/build-push-action@v2
        id: build_editor_image
        with:
          context: .
          file: ./editor/Dockerfile
          build-args: |
            hubImage=localhost:5000/unityci/hub:latest
            baseImage=localhost:5000/unityci/base:latest
            module=${{ matrix.targetPlatform }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: true
          tags: localhost:5000/unityci/editor:latest
      - name: Inspect
        run: |
          docker buildx imagetools inspect localhost:5000/unityci/editor:latest
      #      - name: Image digest
      #        run: echo ${{ steps.build_editor_image.outputs.digest }}
      #      - name: Update DockerHub description
      #        uses: peter-evans/dockerhub-description@v2
      #        with:
      #          username: ${{ secrets.DOCKEReditor_USERNAME }}
      #          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      #          repository: peterevans/dockerhub-description
      #          short-description: $(cat ./editor/100-characters-dockerhub-description.txt)
      #          readme-filepath: ./editor/README.md

      ###########################
      #         Metrics         #
      ###########################
      - name: Disk space after
        if: always()
        run: df -h

  testImages:
    name: 🧪 Test images
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - run: echo "not implemented"
        # TODO - Add test that checks if a license is valid after the changes to a dockerfile (hardware id verification)
