name: PR 😎

on:
  pull_request: {}
#  push: { branches: [main] }

jobs:
  baseImage:
    name: Build unity-ci/base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      #      - name: Login to DockerHub
      #        uses: docker/login-action@v1
      #        with:
      #          username: ${{ secrets.DOCKERHUB_USERNAME }}
      #          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image # and push
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          #push: true
          tags: |
            unity-ci/base:latest
            unity-ci/base:semver
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: List images
        run: docker image ls

  testImages:
    name: Test images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - run: echo "not implemented"
