name: PR 😎

on:
  pull_request: {}
#  push: { branches: [main] }

jobs:
  baseImage:
    name: Build unity-ci/base
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      ###########################
      #          Setup          #
      ###########################
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      #      - name: Login to DockerHub
      #        uses: docker/login-action@v1
      #        with:
      #          username: ${{ secrets.DOCKERHUB_USERNAME }}
      #          password: ${{ secrets.DOCKERHUB_TOKEN }}

      ###########################
      #        Base image       #
      ###########################
      - name: Build base image # and push
        uses: docker/build-push-action@v2
        id: build_base_image
        with:
          context: .
          file: ./base/Dockerfile
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: true
          tags: localhost:5000/unity-ci/base:latest
      - name: Inspect
        run: |
          docker buildx imagetools inspect localhost:5000/unity-ci/base:latest
      #      - name: Image digest
      #        run: echo ${{ steps.build_base_image.outputs.digest }}
      #      - name: Update DockerHub description
      #        uses: peter-evans/dockerhub-description@v2
      #        with:
      #          username: ${{ secrets.DOCKERHUB_USERNAME }}
      #          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      #          repository: peterevans/dockerhub-description
      #          short-description: $(cat ./base/100-characters-dockerhub-description.txt)
      #          readme-filepath: ./base/README.md

      ###########################
      #        Hub image        #
      ###########################
      - name: Build hub image # and push
        uses: docker/build-push-action@v2
        id: build_hub_image
        with:
          context: .
          file: ./hub/Dockerfile
          build-args: baseImage=localhost:5000/unity-ci/base:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: true
          tags: localhost:5000/unity-ci/hub:latest
      - name: Inspect
        run: |
          docker buildx imagetools inspect localhost:5000/unity-ci/hub:latest
      #      - name: Image digest
      #        run: echo ${{ steps.build_hub_image.outputs.digest }}
      #      - name: Update DockerHub description
      #        uses: peter-evans/dockerhub-description@v2
      #        with:
      #          username: ${{ secrets.DOCKERHUB_USERNAME }}
      #          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      #          repository: peterevans/dockerhub-description
      #          short-description: $(cat ./hub/100-characters-dockerhub-description.txt)
      #          readme-filepath: ./hub/README.md

      ###########################
      #       Editor image      #
      ###########################
      - name: Build editor image # and push
        uses: docker/build-push-action@v2
        id: build_editor_image
        with:
          context: .
          file: ./editor/Dockerfile
          build-args: hubImage=localhost:5000/unity-ci/hub:latest,baseImage=localhost:5000/unity-ci/base:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: true
          tags: localhost:5000/unity-ci/editor:latest
      - name: Inspect
        run: |
          docker buildx imagetools inspect localhost:5000/unity-ci/editor:latest
      #      - name: Image digest
      #        run: echo ${{ steps.build_editor_image.outputs.digest }}
      #      - name: Update DockerHub description
      #        uses: peter-evans/dockerhub-description@v2
      #        with:
      #          username: ${{ secrets.DOCKEReditor_USERNAME }}
      #          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      #          repository: peterevans/dockerhub-description
      #          short-description: $(cat ./editor/100-characters-dockerhub-description.txt)
      #          readme-filepath: ./editor/README.md

  testImages:
    name: Test images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - run: echo "not implemented"
